// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// toHTTP
String toHTTP(CharacterVector params);
RcppExport SEXP fbAdsInsightsR_toHTTP(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(toHTTP(params));
    return rcpp_result_gen;
END_RCPP
}
// cvr
NumericVector cvr(NumericVector clicks, NumericVector installs);
RcppExport SEXP fbAdsInsightsR_cvr(SEXP clicksSEXP, SEXP installsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type clicks(clicksSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type installs(installsSEXP);
    rcpp_result_gen = Rcpp::wrap(cvr(clicks, installs));
    return rcpp_result_gen;
END_RCPP
}
// cpi
NumericVector cpi(NumericVector installs, NumericVector spend);
RcppExport SEXP fbAdsInsightsR_cpi(SEXP installsSEXP, SEXP spendSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type installs(installsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type spend(spendSEXP);
    rcpp_result_gen = Rcpp::wrap(cpi(installs, spend));
    return rcpp_result_gen;
END_RCPP
}
// cpl
NumericVector cpl(NumericVector likes, NumericVector spend);
RcppExport SEXP fbAdsInsightsR_cpl(SEXP likesSEXP, SEXP spendSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type likes(likesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type spend(spendSEXP);
    rcpp_result_gen = Rcpp::wrap(cpl(likes, spend));
    return rcpp_result_gen;
END_RCPP
}
// cpa
NumericVector cpa(NumericVector actions, NumericVector spend);
RcppExport SEXP fbAdsInsightsR_cpa(SEXP actionsSEXP, SEXP spendSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type actions(actionsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type spend(spendSEXP);
    rcpp_result_gen = Rcpp::wrap(cpa(actions, spend));
    return rcpp_result_gen;
END_RCPP
}
// createFields
String createFields(CharacterVector x);
RcppExport SEXP fbAdsInsightsR_createFields(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(createFields(x));
    return rcpp_result_gen;
END_RCPP
}
// scopeCheckC
void scopeCheckC(CharacterVector scope, CharacterVector valid);
RcppExport SEXP fbAdsInsightsR_scopeCheckC(SEXP scopeSEXP, SEXP validSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type scope(scopeSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type valid(validSEXP);
    scopeCheckC(scope, valid);
    return R_NilValue;
END_RCPP
}
// buildBreakdowns
String buildBreakdowns(CharacterVector breakdowns, Function f);
RcppExport SEXP fbAdsInsightsR_buildBreakdowns(SEXP breakdownsSEXP, SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type breakdowns(breakdownsSEXP);
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(buildBreakdowns(breakdowns, f));
    return rcpp_result_gen;
END_RCPP
}
// parseP
CharacterVector parseP(CharacterVector param);
RcppExport SEXP fbAdsInsightsR_parseP(SEXP paramSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type param(paramSEXP);
    rcpp_result_gen = Rcpp::wrap(parseP(param));
    return rcpp_result_gen;
END_RCPP
}
// optIt
CharacterVector optIt(String params, Function fp, Function ff, String fct);
RcppExport SEXP fbAdsInsightsR_optIt(SEXP paramsSEXP, SEXP fpSEXP, SEXP ffSEXP, SEXP fctSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< Function >::type fp(fpSEXP);
    Rcpp::traits::input_parameter< Function >::type ff(ffSEXP);
    Rcpp::traits::input_parameter< String >::type fct(fctSEXP);
    rcpp_result_gen = Rcpp::wrap(optIt(params, fp, ff, fct));
    return rcpp_result_gen;
END_RCPP
}
