// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// toHTTP
String toHTTP(CharacterVector params);
RcppExport SEXP fbAdsInsightsR_toHTTP(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type params(paramsSEXP);
    __result = Rcpp::wrap(toHTTP(params));
    return __result;
END_RCPP
}
// cvr
NumericVector cvr(NumericVector clicks, NumericVector installs);
RcppExport SEXP fbAdsInsightsR_cvr(SEXP clicksSEXP, SEXP installsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type clicks(clicksSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type installs(installsSEXP);
    __result = Rcpp::wrap(cvr(clicks, installs));
    return __result;
END_RCPP
}
// cpi
NumericVector cpi(NumericVector installs, NumericVector spend);
RcppExport SEXP fbAdsInsightsR_cpi(SEXP installsSEXP, SEXP spendSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type installs(installsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type spend(spendSEXP);
    __result = Rcpp::wrap(cpi(installs, spend));
    return __result;
END_RCPP
}
// cpl
NumericVector cpl(NumericVector likes, NumericVector spend);
RcppExport SEXP fbAdsInsightsR_cpl(SEXP likesSEXP, SEXP spendSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type likes(likesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type spend(spendSEXP);
    __result = Rcpp::wrap(cpl(likes, spend));
    return __result;
END_RCPP
}
// cpa
NumericVector cpa(NumericVector actions, NumericVector spend);
RcppExport SEXP fbAdsInsightsR_cpa(SEXP actionsSEXP, SEXP spendSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type actions(actionsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type spend(spendSEXP);
    __result = Rcpp::wrap(cpa(actions, spend));
    return __result;
END_RCPP
}
// createFields
String createFields(CharacterVector x);
RcppExport SEXP fbAdsInsightsR_createFields(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    __result = Rcpp::wrap(createFields(x));
    return __result;
END_RCPP
}
// scopeCheckC
void scopeCheckC(CharacterVector scope, CharacterVector valid);
RcppExport SEXP fbAdsInsightsR_scopeCheckC(SEXP scopeSEXP, SEXP validSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type scope(scopeSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type valid(validSEXP);
    scopeCheckC(scope, valid);
    return R_NilValue;
END_RCPP
}
// buildBreakdowns
String buildBreakdowns(CharacterVector breakdowns, Function f);
RcppExport SEXP fbAdsInsightsR_buildBreakdowns(SEXP breakdownsSEXP, SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type breakdowns(breakdownsSEXP);
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    __result = Rcpp::wrap(buildBreakdowns(breakdowns, f));
    return __result;
END_RCPP
}
// parseP
CharacterVector parseP(CharacterVector param);
RcppExport SEXP fbAdsInsightsR_parseP(SEXP paramSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type param(paramSEXP);
    __result = Rcpp::wrap(parseP(param));
    return __result;
END_RCPP
}
