# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute CVR
#' @param clicks Vector of clicks
#' @param installs Vector of installs
cvr <- function(clicks, installs) {
    .Call('fbAdsInsightsR_cvr', PACKAGE = 'fbAdsInsightsR', clicks, installs)
}

#' Compute CPI
#' @param installs Vector of installs
#' @param spend Vector of spend
cpi <- function(installs, spend) {
    .Call('fbAdsInsightsR_cpi', PACKAGE = 'fbAdsInsightsR', installs, spend)
}

#' Compute CPL
#' @param likes Vector of likes
#' @param spend Vector of spend
cpl <- function(likes, spend) {
    .Call('fbAdsInsightsR_cpl', PACKAGE = 'fbAdsInsightsR', likes, spend)
}

#' Compute CPL
#' @param actions Vector of actions
#' @param spend Vector of spend
cpa <- function(actions, spend) {
    .Call('fbAdsInsightsR_cpa', PACKAGE = 'fbAdsInsightsR', actions, spend)
}

createFields <- function(x) {
    .Call('fbAdsInsightsR_createFields', PACKAGE = 'fbAdsInsightsR', x)
}

#' TestScope
#' @param scope Scope to test
#' @param valid Valid scopes to test against
scopeCheckC <- function(scope, valid) {
    invisible(.Call('fbAdsInsightsR_scopeCheckC', PACKAGE = 'fbAdsInsightsR', scope, valid))
}

#' Build http
#' 
#' @param params Parameters
toHTTP <- function(params) {
    .Call('fbAdsInsightsR_toHTTP', PACKAGE = 'fbAdsInsightsR', params)
}

