# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Build http
#' 
#' @param params Parameters
toHTTP <- function(params) {
    .Call('fbAdsInsightsR_toHTTP', PACKAGE = 'fbAdsInsightsR', params)
}

#' Compute CVR
#' @param clicks Vector of clicks
#' @param installs Vector of installs
cvr <- function(clicks, installs) {
    .Call('fbAdsInsightsR_cvr', PACKAGE = 'fbAdsInsightsR', clicks, installs)
}

#' Compute CPI
#' @param installs Vector of installs
#' @param spend Vector of spend
cpi <- function(installs, spend) {
    .Call('fbAdsInsightsR_cpi', PACKAGE = 'fbAdsInsightsR', installs, spend)
}

#' Compute CPL
#' @param likes Vector of likes
#' @param spend Vector of spend
cpl <- function(likes, spend) {
    .Call('fbAdsInsightsR_cpl', PACKAGE = 'fbAdsInsightsR', likes, spend)
}

#' Compute CPL
#' @param actions Vector of actions
#' @param spend Vector of spend
cpa <- function(actions, spend) {
    .Call('fbAdsInsightsR_cpa', PACKAGE = 'fbAdsInsightsR', actions, spend)
}

#' createFields
#' 
#' @param x fields
createFields <- function(x) {
    .Call('fbAdsInsightsR_createFields', PACKAGE = 'fbAdsInsightsR', x)
}

#' scopeCheck
#' @param scope Scope to test
#' @param valid Valid scopes to test against
scopeCheckC <- function(scope, valid) {
    invisible(.Call('fbAdsInsightsR_scopeCheckC', PACKAGE = 'fbAdsInsightsR', scope, valid))
}

#' buildBreakdowns
#' @param breakdowns Breakdowns
#' @param f testParam
buildBreakdowns <- function(breakdowns, f) {
    .Call('fbAdsInsightsR_buildBreakdowns', PACKAGE = 'fbAdsInsightsR', breakdowns, f)
}

#' parseP
#' @param param Parameter to parse
parseP <- function(param) {
    .Call('fbAdsInsightsR_parseP', PACKAGE = 'fbAdsInsightsR', param)
}

#' get options
#' @param params parameters to test
#' @param fp \code{\link{findParams}}
#' @param ff \code{\link{findFields}}
#' @param fct Function passed from parent FUN
optIt <- function(params, fp, ff, fct = "getAny") {
    .Call('fbAdsInsightsR_optIt', PACKAGE = 'fbAdsInsightsR', params, fp, ff, fct)
}

